### ISSUE TITLE
Define this as a constant

### ISSUE THREAD

**Issue by AlexKap23** [pothigai/SlotMachine#4]
https://github.com/pothigai/SlotMachine/blob/d4db5b5e983e135a2e5afcadd5ae813ce8ed8d8e/Program.cs#L22

There should be no hardcoded things inside your code. Define constants for cases like this. 

There are also 3-4 other hardcoded strings that can be converted to constants.

**Comment by pothigai** [comment]
But I use the playAgain as a variable, I use it to collect the user input and check if it's "yes" or "no". Or do you mean I should define a constant for the "yes" or "no"?

**Comment by AlexKap23** [comment]
Yes this is exaclty what I mean. Define a constant for the "y" and for "n" and use it. There are at least 6 usages of "y" in your code. 

In general U should avoid hardcoded strings in your code.
